<?php

namespace webd\stats;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-09 at 10:28:10.
 */
class NormalDistributionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var NormalDistribution
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new NormalDistribution;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\stats\NormalDistribution::getMean
     * @todo   Implement testGetMean().
     */
    public function testGetMean() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\stats\NormalDistribution::getStandardDeviation
     * @todo   Implement testGetStandardDeviation().
     */
    public function testGetStandardDeviation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\stats\NormalDistribution::getVariance
     * @todo   Implement testGetVariance().
     */
    public function testGetVariance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\stats\NormalDistribution::cumulativeProbability
     */
    public function testCumulativeProbability() {
        $nd = new NormalDistribution(0, 1);
        $this->assertEquals(
                0.0228, 
                $nd->cumulativeProbability(-2),
                "",
                0.001);
        $this->assertEquals(
                0.1587, 
                $nd->cumulativeProbability(-1),
                "",
                0.001);
        $this->assertEquals(
                0.5, 
                $nd->cumulativeProbability(0),
                "",
                0.001);
        $this->assertEquals(
                0.8413, 
                $nd->cumulativeProbability(1),
                "",
                0.001);
        $this->assertEquals(
                0.9772, 
                $nd->cumulativeProbability(2),
                "",
                0.001);
        
    }

    /**
     * @covers webd\stats\NormalDistribution::sample
     * @todo   Implement testSample().
     */
    public function testSample() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\stats\NormalDistribution::samples
     * @todo   Implement testSamples().
     */
    public function testSamples() {
        $d = new NormalDistribution(2, 5);
        $s = $d->samples(1000);
        //echo implode("\t", $s);
    }

}
