<?php

namespace webd\stats;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-09 at 10:28:10.
 */
class RandomTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Random
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Random;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\stats\Random::gaussian
     * @todo   Implement testGaussian().
     */
    public function testGaussian() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers webd\stats\Random::uniform
     * @todo   Implement testUniform().
     */
    public function testUniform() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
