<?php

namespace webd\stats;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-09 at 10:28:10.
 */
class StatsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Stats
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Stats;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers webd\stats\Stats::bic
     * @todo   Implement testBic().
     */
    public function testBic() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
